server:
  port: 8091



spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
          jwk-set-uri: http://127.0.0.1:9000/.well-known/jwks.json


logging:
  level:
    root: debug








